order_process/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

admin.site.site_header = 'ORDER PROCESS'
app_name = "order_process"
urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('api/v1/', include('order_process_app.urls')),
    path('', include('pages.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/v2/', include('routers.urls')),
]

order_process_app/urls.py
import routers as routers
from django.urls import path
from . import views


app_name = 'app_html'
routers = routers.DefaultRouter()
routers.register('employee', views.EmployeesViewSet)

urlpatterns = [
    path('employees-list/', views.EmployeesViewSet, name='employees-list'),
    path('employee-detail/<int:pk>/', views.EmployeesViewSet, name='employees-details'),
]

pages/urls.py
from django.urls import path

from .views import home_view
app_name="pages"
urlpatterns = [
    path('', home_view, name='home-page'),
]

order_process_app/models.py
from unicodedata import category

from django.db import models


# Create your models here.
class Suppliers(models.Model):
    REGIONS = (
        ('SOUTH_SOUTH', 'South South'),
        ('SOUTH_WEST', 'South West'),
        ('SOUTH_EAST', 'South East'),
        ('NORTH_EAST', 'North East'),
        ('NORTH_WEST', 'North West'),
        ('NORTH_CENTRAL', 'North Central')
    )
    company_name = models.CharField(max_length=255, verbose_name="Company Name")
    contact_name = models.CharField(max_length=255, verbose_name="Contact Name")
    contact_title = models.CharField(max_length=255, verbose_name="Contact Title")
    address = models.CharField(max_length=255, verbose_name="Address")
    city = models.CharField(max_length=255, verbose_name="City")
    region = models.CharField(max_length=255, verbose_name="Regions", choices=REGIONS)
    postal_code = models.CharField(max_length=255, verbose_name="Postal Code")
    country = models.CharField(max_length=255, verbose_name="Country")
    phone = models.PositiveBigIntegerField()
    fax = models.PositiveSmallIntegerField()
    home_page = models.CharField(max_length=255, verbose_name="Home Page")


class Category(models.Model):
    category_name = models.CharField(max_length=255, verbose_name="Category Name")
    description = models.CharField(max_length=255, verbose_name="Description")


class Products(models.Model):
    REORDER_LEVEL = (
        ('HIGH', 'High'),
        ('LOW', 'Low'),
        ('MEDIUM', 'Medium')
    )
    supplier_id = models.ForeignKey(Suppliers, on_delete=models.CASCADE)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=255, verbose_name="Product Name")
    quantity_per_unit = models.IntegerField()
    unit_price = models.DecimalField(max_digits=8, decimal_places=2)
    units_in_stock = models.IntegerField()
    units_on_order = models.IntegerField()
    reorder_level = models.CharField(max_length=255, verbose_name="Reorder Level", choices=REORDER_LEVEL)


class Customers(models.Model):
    company_name = models.CharField(max_length=255, verbose_name="Company Name")
    contact_name = models.CharField(max_length=255, verbose_name="Contact Name")
    contact_title = models.CharField(max_length=255, verbose_name="Contact Title")
    address = models.CharField(max_length=255, verbose_name="Address")
    city = models.CharField(max_length=255, verbose_name="City")
    region = models.CharField(max_length=255, verbose_name="Region")
    postal_code = models.PositiveSmallIntegerField()
    country = models.CharField(max_length=255, verbose_name="Country")
    phone = models.CharField(max_length=255, verbose_name="Phone")
    fax = models.CharField(max_length=255, verbose_name="Fax")


class Employees(models.Model):
    last_name = models.CharField(max_length=255, verbose_name="Last Name")
    first_name = models.CharField(max_length=255, verbose_name="First Name")
    title = models.CharField(max_length=25, verbose_name="Title")
    title_of_courtesy = models.CharField(max_length=25, verbose_name="Title Of Courtesy")
    birthday = models.DateField()
    hire_date = models.DateField(auto_now_add=True)
    address = models.CharField(max_length=255, verbose_name="Address")
    city = models.CharField(max_length=255, verbose_name="City")
    region = models.CharField(max_length=255, verbose_name="Region")
    postal_code = models.PositiveSmallIntegerField()
    country = models.CharField(max_length=255, verbose_name="Country")
    home_page = models.CharField(max_length=255, verbose_name="Home Page")
    extension = models.CharField(max_length=255, verbose_name="Extension")
    photo = models.CharField(max_length=255, verbose_name="Photo")
    notes = models.CharField(max_length=255, verbose_name="Notes")
    reports_to = models.CharField(max_length=255, verbose_name="Reports To")


class Shippers(models.Model):
    company_name = models.CharField(max_length=255, verbose_name="Company Name")
    phone = models.CharField(max_length=255, verbose_name="Phone")


class Orders(models.Model):
    customer_id = models.ForeignKey(Customers, on_delete=models.CASCADE)
    employees_id = models.ForeignKey(Employees, on_delete=models.CASCADE)
    shippers_id = models.ForeignKey(Shippers, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    required_date = models.DateTimeField()
    shipped_date = models.DateTimeField(auto_now_add=True)
    freight_date = models.PositiveBigIntegerField()
    ship_name = models.CharField(max_length=255, verbose_name="Ship Name")
    ship_Address = models.CharField(max_length=255, verbose_name="ShipAddress")
    ship_city = models.CharField(max_length=255, verbose_name="Ship City")
    ship_region = models.CharField(max_length=255, verbose_name="Ship Region")
    ship_postal_code = models.PositiveSmallIntegerField()
    ship_country = models.CharField(max_length=255, verbose_name="Ship Country")


class OrderDetail(models.Model):
    order_id = models.ForeignKey(Orders, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    unit_price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.IntegerField()
    discount = models.DecimalField(max_digits=8, decimal_places=2)

pages/models.py
from django.db import models

# Create your models here.

order_process_app/views.py
from rest_framework import viewsets
from . import serializer

from order_process_app import models


class EmployeesViewSet(viewsets.ModelViewSet):
    queryset = models.Employees.objects.all()
    serializer_class = serializer.EmployeesSerializer

pages/views.py
from django.http import HttpResponse
from django.shortcuts import render

from order_process_app.templates import order_process_app_html


# Create your views here.
def home_view(request):
    return render(request, 'order_process_app_html/home.html')

order_process_app/templates/order_process_app_html/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Page</title>
</head>
<body>

</body>
</html>

order_process_app/templates/order_process_app_html/contact_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact us Page</title>
</head>
<body>

</body>
</html>

order_process_app/templates/order_process_app_html/employee-details.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Employee Details</title>
</head>
<body>
    <h1>Welcome, {{ employee.last_name }}</h1> </h1>
    <h2>These are your information</h2>
    <p>
        {{ employee.title }} {{ employee.first_name }}, {{ employee.last_name }}
        {{ employe.birthdate }}
        {{ employe.hire_date }}
        {{ employe.address }}
        {{ employe.city }}
        {{ employe.region }}
        {{ employe.country }}
        {{ employe.home_page }}
        {{ employe.notes }}
        {{ employe.reports_to }}

    </p>
</body>
</html>

order_process_app/templates/order_process_app_html/employees-details.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Employee Details</title>
</head>
<body>
    <h1>Welcome, {{ employee.last_name }}</h1> </h1>
    <h2>These are your information</h2>
    <p>
        {{ employee.title }} {{ employee.first_name }}, {{ employee.last_name }}
        {{ employe.birthdate }}
        {{ employe.hire_date }}
        {{ employe.address }}
        {{ employe.city }}
        {{ employe.region }}
        {{ employe.country }}
        {{ employe.home_page }}
        {{ employe.notes }}
        {{ employe.reports_to }}

    </p>
</body>
</html>

order_process_app/templates/order_process_app_html/employees-list.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/order_process.css' %}">
    <title>Employee List</title>
</head>
<body>
 <ul>
     {% for employee in employees%}
         <li><a href="{% url 'app_html:employees-details' employee.pk %}">{{ employee.title }}  {{ employee.last_name }}</a></li>
     {% endfor %}
 </ul>
</body>
</html>

order_process_app/templates/order_process_app_html/home.html
{%  extends 'base.html' %}
{% block head %}
    <title>Home Page</title>
{% endblock %}
{% block content%}
    <h1>Welcome to home page</h1>
{% endblock %}

order_process_app/templates/order_process_app_html/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Page</title>
</head>
<body>

</body>
</html>

order_process_app/templates/order_process_app_html/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product Page</title>
</head>
<body>

</body>
</html>

order_process_app/templates/order_process_app_html/ship.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ship Page</title>
</head>
<body>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base Template</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    <div>
        <h1>From tha base template</h1>
    </div>
    <div class="header-container">
        <a>Home</a>
        <a>Order</a>
        <a>Product</a>
        <a>Ships</a>
        <a>Contact us</a>
        <a>About us</a>
    </div>
    <hr>
    {% block content%}
    {% endblock %}
</body>
</html>